//! JA4 Encrypted Traffic Analyzer — Production Implementation
//!
//! Axis 2: Replaces the mock implementation with the full FingerprintEngine.
//! Integrates JA4 client fingerprinting, malicious-JA4 database lookup,
//! and automatic Sigma rule injection for new detections.

use anyhow::Result;
use std::sync::Arc;
use std::collections::HashSet;
use tracing::{info, warn};
use tokio::sync::RwLock;

use crate::fingerprint::{FingerprintEngine, FingerprintHit, FingerprintKind};
use crate::fingerprint::ja4::{parse_client_hello, Ja4Fingerprint};
use crate::detection::DetectionEngine;

pub struct Ja4Analyzer {
    engine: FingerprintEngine,
    detection_engine: Arc<DetectionEngine>,
}

impl Ja4Analyzer {
    pub fn new(detection_engine: Arc<DetectionEngine>) -> Self {
        Self {
            engine: FingerprintEngine::new(),
            detection_engine,
        }
    }

    /// Analyse a raw TLS ClientHello payload and return a hit if malicious.
    pub async fn analyze_tls_payload(
        &self,
        pid: u32,
        comm: &str,
        payload: &[u8],
        src_ip: &str,
        dst_ip: &str,
        dst_port: u16,
    ) -> Result<Option<FingerprintHit>> {
        let hit = self.engine.analyse_tls_client(payload, src_ip, dst_ip, dst_port);

        if let Some(ref h) = hit {
            info!(
                comm = comm,
                pid = pid,
                fp = %h.fingerprint,
                malicious = h.is_malicious,
                "TLS JA4 fingerprint"
            );

            if h.is_malicious {
                warn!(
                    comm = comm,
                    pid = pid,
                    fp = %h.fingerprint,
                    "🚨 MALICIOUS JA4 fingerprint detected — auto-generating Sigma rule"
                );
                // Inject a detection rule into the live Sigma engine
                self.inject_ja4_rule(comm, dst_ip, &h.fingerprint).await;
            }
        }

        Ok(hit)
    }

    /// Add a custom malicious JA4 fingerprint at runtime.
    pub fn add_malicious_fingerprint(&mut self, fp: String) {
        self.engine.add_malicious_ja4(fp);
    }

    /// Returns top-N fingerprints seen (for dashboard analytics).
    pub fn top_fingerprints(&self, n: usize) -> Vec<(String, u64)> {
        self.engine.top_fingerprints(n)
    }

    pub fn malicious_db_size(&self) -> usize {
        self.engine.malicious_db_size()
    }

    // ── Private ──────────────────────────────────────────────────────────────

    async fn inject_ja4_rule(&self, process: &str, dst_ip: &str, ja4: &str) {
        // Generate a Sigma-compatible YAML rule for this JA4 fingerprint
        let yaml = format!(
            r#"title: Malicious JA4 TLS Fingerprint from {process}
id: auto-{ja4}
status: experimental
description: >
  Automatically generated by ThorIDS after detecting a known-malicious
  JA4 fingerprint from process '{process}' to {dst_ip}.
  JA4: {ja4}
logsource:
  category: network
  product: thor
detection:
  selection:
    dst_ip: "{dst_ip}"
    ja4_hash: "{ja4}"
  condition: selection
level: high
tags:
  - attack.command_and_control
  - auto-generated
"#,
            process = process,
            dst_ip = dst_ip,
            ja4 = ja4,
        );

        let rule = crate::detection::sigma::GuardedDynamicRule {
            id: format!("auto-{}", ja4),
            yaml_content: yaml,
            title: format!("Auto-JA4: {}", ja4),
            mode: crate::detection::sigma::RuleMode::Enforce,
            created_at: std::time::Instant::now(),
            match_count: Arc::new(std::sync::atomic::AtomicUsize::new(0)),
            max_matches_per_minute: 100,
            shadow_duration_secs: 0,
            source: crate::detection::sigma::RuleSource::AutoGenerated,
        };

        match self.detection_engine.inject_sigma_rule(rule) {
            Ok(_) => info!("✅ Sigma rule injected for JA4: {}", ja4),
            Err(e) => warn!("Failed to inject JA4 Sigma rule: {}", e),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fingerprint_engine_has_known_bad() {
        let engine = FingerprintEngine::new();
        assert!(engine.malicious_db_size() > 0);
    }

    #[test]
    fn ja4_parsed_from_hello() {
        // Build a minimal synthetic ClientHello and verify we get a fingerprint
        use crate::fingerprint::ja4::ClientHello;
        let hello = ClientHello {
            tls_version: 0x0303,
            supported_versions: vec![0x0304],
            cipher_suites: vec![0xc02b, 0xc02c],
            extensions: vec![0x0000, 0x000a, 0x000d],
            sni: Some("example.com".to_string()),
            alpn: vec!["h2".to_string()],
            signature_algorithms: vec![0x0403],
            supported_groups: vec![0x001d],
        };
        let fp = Ja4Fingerprint::from_parsed(&hello);
        assert!(!fp.fingerprint.is_empty());
        assert_eq!(fp.sni_flag, 'd');
    }
}
