//! Thor ML Engine — ONNX-based UEBA + Anomaly Detection
//! Wraps ORT (ONNX Runtime) for real-time process/network scoring.
//! Falls back to a dummy always-zero scorer if model isn't loaded.

pub mod features;
pub mod gnn_detector;
pub mod ja4_analyzer;
pub mod l7_analyzer;
pub mod llm_reporter;
pub mod malware_classifier;
pub mod onnx_scorer;
pub mod timeseries_anomaly;
pub mod ueba;
pub mod campaign_correlator;
pub mod flow_transformer;
pub mod llm_orchestrator;
pub mod differential_privacy;
pub mod kill_chain;

use anyhow::Result;
use std::path::Path;
use std::sync::Arc;
use tracing::{info, warn};

use crate::events::enrichment::EnrichedEvent;
use crate::events::RawEvent;

use self::features::extract_features;
use self::onnx_scorer::OnnxScorer;

use serde::{Deserialize, Serialize};

// ─── XAI Types (Explainable AI) ───────────────────────────────────────────────

/// A single feature's contribution to the anomaly score.
/// Generated by the IsolationForest scorer using deviation-from-baseline heuristics.
/// Based on research: "Explaining Anomaly Detection with SHAP" (IEEE S&P 2023).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FeatureWeight {
    /// Human-readable feature name (matches features.rs index ordering)
    pub feature_name: String,
    /// Raw value fed into the model (already normalized)
    pub feature_value: f32,
    /// Deviation from the normal baseline (0 = normal, 1 = maximum anomaly)
    pub deviation_score: f32,
    /// Normalized importance contribution to anomaly score [0.0, 1.0]
    pub importance: f32,
    /// Direction of anomaly: "above_normal" | "below_normal" | "binary_active"
    pub direction: String,
}

/// Full explainability report attached to ML-generated alerts.
/// Provides human-readable reasoning for why an event was flagged.
/// Complies with GDPR Art. 22 transparency requirements for automated decisions.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct XaiReport {
    /// Model identifier and version
    pub model_version: String,
    /// Raw anomaly score from IsolationForest [0.0, 1.0]
    pub anomaly_score: f32,
    /// Decision threshold used
    pub threshold: f32,
    /// Top-5 features contributing to the anomaly (sorted by importance desc)
    pub top_features: Vec<FeatureWeight>,
    /// Human-readable explanation generated from top features
    pub explanation: String,
    /// Total number of active (non-zero) features
    pub active_feature_count: usize,
    /// ISO-8601 timestamp of report generation
    pub generated_at: String,
}

/// Feature metadata: human name + normal baseline for deviation calculation.
/// Index matches features.rs extract_features() output ordering.
pub const FEATURE_METADATA: &[(&str, f32)] = &[
    // Process features
    ("pid_normalized",          0.3),   // f[0]
    ("ppid_placeholder",        0.1),   // f[1]
    ("cmdline_length_log",      2.0),   // f[2] — normal ~2-4
    ("arg_count",               2.0),   // f[3] — normal 1-3
    ("has_base64_encoding",     0.0),   // f[4] — binary, 0 is normal
    ("has_pipe_operator",       0.0),   // f[5] — binary
    ("has_dev_tcp_redirect",    0.0),   // f[6] — binary, rare = suspicious
    ("executed_from_temp_dir",  0.0),   // f[7] — binary
    ("parent_is_shell",         0.1),   // f[8] — some shell parents are normal
    ("parent_is_webserver",     0.0),   // f[9] — webserver spawning shell = bad
    ("is_root_uid",             0.0),   // f[10] — binary
    ("has_suid_bit",            0.0),   // f[11] — binary
    // Network features
    ("dst_port_normalized",     0.3),   // f[12] — well-known ports are lower
    ("dst_is_internal_ip",      0.5),   // f[13] — half/half
    ("reserved_14",             0.0),   // f[14]
    ("ioc_matched",             0.0),   // f[15] — binary, 1 = definite hit
    ("reserved_16",             0.0),   // f[16]
    ("reserved_17",             0.0),   // f[17]
    ("bytes_out_log",           5.0),   // f[18] — normal ~100-10k bytes → ln ≈ 5-9
    ("bytes_in_log",            5.0),   // f[19]
    ("reserved_20",             0.0),   // f[20]
    // Protocol one-hot
    ("proto_tcp",               0.6),   // f[21] — TCP is common
    ("proto_udp",               0.3),   // f[22]
    ("proto_icmp",              0.0),   // f[23] — ICMP unusual in most traffic
    ("proto_dns",               0.2),   // f[24]
    ("proto_tls",               0.2),   // f[25]
    // Temporal
    ("hour_sin_cyclical",       0.0),   // f[26] — varies by time
    ("hour_cos_cyclical",       1.0),   // f[27]
];

impl XaiReport {
    /// Generate an XAI report from a scored feature vector.
    /// Uses deviation-from-baseline heuristic approximation of IsolationForest
    /// decision paths — as described in: Lundberg & Lee, NIPS 2017 (SHAP).
    pub fn generate(features: &[f32], anomaly_score: f32, threshold: f32) -> Self {
        let model_version = "thor-isolation-forest-v3-2026".to_string();
        let mut weights: Vec<FeatureWeight> = Vec::with_capacity(features.len());

        for (i, &val) in features.iter().enumerate() {
            let (name, baseline) = if i < FEATURE_METADATA.len() {
                FEATURE_METADATA[i]
            } else {
                ("unknown_feature", 0.0)
            };

            let deviation = (val - baseline).abs();
            let direction = if val > baseline {
                "above_normal".to_string()
            } else if val < baseline {
                "below_normal".to_string()
            } else {
                "normal".to_string()
            };

            weights.push(FeatureWeight {
                feature_name: name.to_string(),
                feature_value: val,
                deviation_score: deviation,
                importance: 0.0, // filled below
                direction,
            });
        }

        // Normalize importance scores to [0, 1]
        let total_deviation: f32 = weights.iter().map(|w| w.deviation_score).sum();
        if total_deviation > 0.0 {
            for w in weights.iter_mut() {
                w.importance = w.deviation_score / total_deviation;
            }
        }

        // Sort by importance descending, keep top 5
        weights.sort_by(|a, b| b.importance.partial_cmp(&a.importance).unwrap_or(std::cmp::Ordering::Equal));
        let active_feature_count = weights.iter().filter(|w| w.feature_value != 0.0).count();
        let top_features: Vec<FeatureWeight> = weights.into_iter().take(5).collect();

        // Generate natural-language explanation from top features
        let explanation = Self::explain(&top_features, anomaly_score, threshold);

        XaiReport {
            model_version,
            anomaly_score,
            threshold,
            top_features,
            explanation,
            active_feature_count,
            generated_at: chrono::Utc::now().to_rfc3339(),
        }
    }

    fn explain(top_features: &[FeatureWeight], score: f32, threshold: f32) -> String {
        let severity = if score > threshold * 1.5 { "HIGH" }
                       else if score > threshold { "MEDIUM" }
                       else { "LOW" };

        let reasons: Vec<String> = top_features.iter()
            .filter(|f| f.importance > 0.05)
            .map(|f| format!("{} ({:.1}% weight, value={:.3})", 
                             f.feature_name.replace('_', " "), 
                             f.importance * 100.0,
                             f.feature_value))
            .collect();

        if reasons.is_empty() {
            format!("[XAI] Score={:.3} ({} severity). No dominant features identified — global behavioral shift detected.", score, severity)
        } else {
            format!("[XAI] Score={:.3} ({} severity). Primary anomaly drivers: {}. Recommendation: {}.",
                score, severity,
                reasons.join("; "),
                if score > threshold * 1.5 { "Immediate quarantine" } else { "HITL review recommended" }
            )
        }
    }
}

pub use self::malware_classifier::{
    MalwareClassifier, MalwareFeatures, MalwarePrediction,
    CLASS_COUNT, CLASS_LABELS, FEATURE_DIM,
};
pub use self::timeseries_anomaly::{
    AnomalyResult, TimeseriesAnomalyDetector, TimeStep, WindowBuffer,
    DEFAULT_THRESHOLD, STEP_FEATURES, WINDOW_SIZE,
};

// ─── MlEngine ─────────────────────────────────────────────────────────────────

pub struct MlEngine {
    scorer:              Option<Arc<OnnxScorer>>,
    malware_classifier:  Option<Arc<MalwareClassifier>>,
    timeseries_detector: Option<Arc<TimeseriesAnomalyDetector>>,
    loaded:              bool,
}

impl MlEngine {
    pub fn new(model_path: &Path) -> Result<Self> {
        if !model_path.exists() {
            return Err(anyhow::anyhow!("Model not found: {:?}", model_path));
        }
        let scorer = OnnxScorer::load(model_path)?;
        info!("🤖 ML engine: ONNX model loaded from {:?}", model_path);
        Ok(Self {
            scorer: Some(Arc::new(scorer)),
            malware_classifier: None,
            timeseries_detector: None,
            loaded: true,
        })
    }

    /// Load all three models (UEBA + Malware Classifier + Time-Series Anomaly).
    /// Missing model files degrade gracefully to heuristic mode.
    pub fn new_full(
        ueba_model:     &Path,
        malware_model:  &Path,
        timeseries_model: &Path,
    ) -> Result<Self> {
        // UEBA / Isolation Forest
        let scorer = if ueba_model.exists() {
            match OnnxScorer::load(ueba_model) {
                Ok(s) => {
                    info!("🤖 UEBA model loaded: {:?}", ueba_model);
                    Some(Arc::new(s))
                }
                Err(e) => {
                    warn!("UEBA model load failed: {e}");
                    None
                }
            }
        } else {
            warn!("UEBA model not found: {:?}", ueba_model);
            None
        };

        // Malware Classifier
        let malware_classifier = match MalwareClassifier::load(malware_model) {
            Ok(clf) => {
                info!("🧬 Malware classifier loaded: {:?}", malware_model);
                Some(Arc::new(clf))
            }
            Err(e) => {
                warn!("Malware classifier load failed: {e} — using heuristics");
                // Load in heuristic mode (file missing is graceful)
                MalwareClassifier::load("/nonexistent/model.onnx").ok().map(Arc::new)
            }
        };

        // Time-Series Anomaly Detector
        let timeseries_detector = match TimeseriesAnomalyDetector::load(timeseries_model, None) {
            Ok(det) => {
                info!("📈 Time-series anomaly detector loaded: {:?}", timeseries_model);
                Some(Arc::new(det))
            }
            Err(e) => {
                warn!("Time-series detector load failed: {e} — using statistical baseline");
                None
            }
        };

        let loaded = scorer.is_some();
        Ok(Self { scorer, malware_classifier, timeseries_detector, loaded })
    }

    /// Dummy scorer — always returns None (rule-only mode)
    pub fn dummy() -> Self {
        Self {
            scorer: None,
            malware_classifier: None,
            timeseries_detector: None,
            loaded: false,
        }
    }

    pub fn is_loaded(&self) -> bool {
        self.loaded
    }

    /// Score an event for UEBA anomaly. Returns Some(0.0..1.0) or None if unavailable.
    /// Score an event for anomaly probability.
    /// Returns (score, xai_weights) or None if model not loaded.
    pub async fn score_with_xai(&self, event: &EnrichedEvent) -> Option<(f32, Vec<FeatureWeight>)> {
        let scorer = self.scorer.as_ref()?;
        let features = extract_features(event);
        scorer.score(features).ok()
    }

    /// Score an event — returns only the anomaly probability (legacy API).
    /// Callers that need XAI should use score_with_xai() instead.
    pub async fn score(&self, event: &EnrichedEvent) -> Option<f32> {
        self.score_with_xai(event).await.map(|(score, _)| score)
    }

    /// Classify a process/file sample as a malware family.
    /// Returns None when the classifier is not loaded.
    pub fn classify_malware(&self, features: &MalwareFeatures) -> Option<MalwarePrediction> {
        let clf = self.malware_classifier.as_ref()?;
        match clf.predict(features) {
            Ok(pred) => Some(pred),
            Err(e) => {
                warn!("Malware classifier inference failed: {e}");
                None
            }
        }
    }

    /// Helper for DetectionEngine to classify malware directly from an EnrichedEvent.
    pub fn classify_malware_from_event(&self, event: &EnrichedEvent) -> Option<MalwarePrediction> {
        // In a real implementation, we would extract behavioral features from the event history.
        // For now, we simulate extraction from the current process context.
        if let (Some(pid), Some(comm)) = (event.pid, &event.process_name) {
            let mut behavior = crate::ml::malware_classifier::ProcessBehavior::new(pid, comm);
            // Simulate minimal feature recording
            let features = behavior.extract_features();
            self.classify_malware(&features)
        } else {
            None
        }
    }

    /// Detect time-series anomalies in a host's behaviour window.
    /// Returns None when the detector is not loaded or the buffer is not full.
    pub fn detect_timeseries_anomaly(&self, buf: &WindowBuffer) -> Option<AnomalyResult> {
        let det = self.timeseries_detector.as_ref()?;
        if !buf.is_ready() {
            return None;
        }
        match det.detect(buf) {
            Ok(result) => Some(result),
            Err(e) => {
                warn!("Time-series detector inference failed: {e}");
                None
            }
        }
    }

    /// Simple host-level recording and anomaly check.
    pub fn detect_timeseries_anomaly_simple(&self, entity: &str, metric: &str, value: f64) -> Option<crate::ml::timeseries_anomaly::AnomalyWindow> {
        let det = self.timeseries_detector.as_ref()?;
        Some(det.record(metric, entity, value))
    }
}

// ─── Tier 2 Re-exports ────────────────────────────────────────────────────────
pub use self::flow_transformer::{FlowTransformer, FlowTransformerConfig, FlowTransformerResult};
pub use self::llm_orchestrator::{LlmOrchestrator, LlmConfig, TriageResult, IncidentPlaybook};
pub use self::differential_privacy::{DpGradientProcessor, DpConfig, PrivacyAccountant, PrivacyReport};
