//! Zero-Day Detection API — REST handlers for Axis 4.
//!
//! # Routes (all require authentication)
//!
//! | Method | Path                             | Auth     | Description                        |
//! |--------|----------------------------------|----------|------------------------------------|
//! | GET    | /api/v1/zeroday/profiles         | analyst  | All active behavioral profiles      |
//! | POST   | /api/v1/zeroday/ingest           | admin    | Inject a synthetic syscall event    |
//! | GET    | /api/v1/zeroday/alerts           | analyst  | Retrieve recent zero-day alerts     |
//! | GET    | /api/v1/zeroday/drift            | analyst  | KL-divergence drift for all PIDs    |
//! | GET    | /api/v1/zeroday/status           | analyst  | Engine health and statistics        |

use std::sync::Arc;

use axum::{
    extract::{Extension, Json, Path, Query},
    http::StatusCode,
    response::IntoResponse,
};
use serde::{Deserialize, Serialize};
use tokio::sync::RwLock;
use tracing::{info, warn};

use crate::detection::zero_day::{
    ZeroDayAlert, ZeroDayEngine, ZeroDaySeverity, DetectionMethod,
    syscall_profiler::{ProcessProfile, SyscallEvent},
};

// ─── Shared state ─────────────────────────────────────────────────────────────

/// Shared state for the zero-day API — injected via Axum extension.
pub struct ZeroDayApiState {
    pub engine: Arc<ZeroDayEngine>,
    /// Ring buffer of recent alerts (capped at MAX_ALERTS).
    pub recent_alerts: RwLock<Vec<ZeroDayAlert>>,
}

const MAX_ALERTS: usize = 1000;

impl ZeroDayApiState {
    pub fn new(engine: Arc<ZeroDayEngine>) -> Arc<Self> {
        Arc::new(Self {
            engine,
            recent_alerts: RwLock::new(Vec::new()),
        })
    }

    /// Push alerts into the ring buffer, evicting oldest if full.
    pub async fn push_alerts(&self, alerts: Vec<ZeroDayAlert>) {
        if alerts.is_empty() { return; }
        let mut buf = self.recent_alerts.write().await;
        buf.extend(alerts);
        if buf.len() > MAX_ALERTS {
            let excess = buf.len() - MAX_ALERTS;
            buf.drain(0..excess);
        }
    }
}

// ─── Request / Response types ─────────────────────────────────────────────────

#[derive(Debug, Deserialize)]
pub struct IngestRequest {
    /// PID of the process generating the event.
    pub pid:        u32,
    /// Process name (comm).
    pub comm:       String,
    /// Linux syscall number.
    pub syscall_nr: u32,
    /// Return value (optional).
    #[serde(default)]
    pub ret_val:    i64,
    /// Byte count for I/O syscalls (optional).
    #[serde(default)]
    pub byte_count: u64,
    /// Timestamp in nanoseconds (optional — defaults to 0).
    #[serde(default)]
    pub ts_ns:      u64,
}

#[derive(Debug, Serialize)]
pub struct IngestResponse {
    /// Number of alerts generated by this event.
    pub alerts_generated: usize,
    /// The alerts themselves (may be empty for normal behaviour).
    pub alerts: Vec<ZeroDayAlert>,
}

#[derive(Debug, Deserialize)]
pub struct AlertsQuery {
    /// Filter by severity (LOW, MEDIUM, HIGH, CRITICAL).
    pub severity: Option<String>,
    /// Filter by PID.
    pub pid: Option<u32>,
    /// Maximum number of results (default: 100).
    #[serde(default = "default_limit")]
    pub limit: usize,
}

fn default_limit() -> usize { 100 }

#[derive(Debug, Serialize)]
pub struct ProfilesResponse {
    pub count:    usize,
    pub profiles: Vec<ProfileSummary>,
}

#[derive(Debug, Serialize)]
pub struct ProfileSummary {
    pub pid:                  u32,
    pub process_name:         String,
    pub event_count:          u64,
    pub unique_syscalls:      usize,
    pub syscall_rate_ema:     f64,
    pub child_spawns:         u64,
    pub memory_alloc_events:  u64,
    pub dangerous_syscalls:   u64,
    pub total_network_bytes:  u64,
    pub write_entropy:        f64,
}

impl From<&ProcessProfile> for ProfileSummary {
    fn from(p: &ProcessProfile) -> Self {
        Self {
            pid:                 p.pid,
            process_name:        p.process_name.clone(),
            event_count:         p.event_count,
            unique_syscalls:     p.unique_syscall_count,
            syscall_rate_ema:    p.syscall_rate_ema,
            child_spawns:        p.child_spawns,
            memory_alloc_events: p.memory_alloc_events,
            dangerous_syscalls:  p.dangerous_syscall_count,
            total_network_bytes: p.total_network_bytes,
            write_entropy:       p.write_entropy_estimate,
        }
    }
}

#[derive(Debug, Serialize)]
pub struct DriftResponse {
    pub count:  usize,
    pub drifts: Vec<DriftEntry>,
}

#[derive(Debug, Serialize)]
pub struct DriftEntry {
    pub pid:           u32,
    pub kl_divergence: f64,
}

#[derive(Debug, Serialize)]
pub struct StatusResponse {
    pub engine_version:   &'static str,
    pub active_profiles:  usize,
    pub total_alerts:     usize,
    pub isolation_trees:  usize,
    pub anomaly_threshold: f64,
}

// ─── Handler: GET /api/v1/zeroday/profiles ────────────────────────────────────

pub async fn get_profiles(
    Extension(state): Extension<Arc<ZeroDayApiState>>,
) -> impl IntoResponse {
    let profiles: Vec<ProfileSummary> = state.engine
        .all_profiles()
        .iter()
        .map(ProfileSummary::from)
        .collect();

    let count = profiles.len();
    info!("GET /api/v1/zeroday/profiles → {} profiles", count);

    (
        StatusCode::OK,
        Json(ProfilesResponse { count, profiles }),
    )
}

// ─── Handler: POST /api/v1/zeroday/ingest ─────────────────────────────────────

pub async fn ingest_event(
    Extension(state): Extension<Arc<ZeroDayApiState>>,
    Json(req):        Json<IngestRequest>,
) -> impl IntoResponse {
    // Validate PID
    if req.pid == 0 {
        warn!("Ingest rejected: PID 0 is invalid");
        return (
            StatusCode::BAD_REQUEST,
            Json(serde_json::json!({ "error": "PID 0 is not a valid process ID" })),
        ).into_response();
    }

    // Validate syscall number (Linux x86-64 max is ~450)
    if req.syscall_nr > 500 {
        return (
            StatusCode::BAD_REQUEST,
            Json(serde_json::json!({
                "error": format!("Syscall number {} exceeds maximum (500)", req.syscall_nr)
            })),
        ).into_response();
    }

    let event = SyscallEvent {
        pid:        req.pid,
        tgid:       req.pid,
        syscall_nr: req.syscall_nr,
        ret_val:    req.ret_val,
        byte_count: req.byte_count,
        ts_ns:      req.ts_ns,
        comm:       req.comm.clone(),
        is_kernel:  false,
    };

    let alerts = state.engine.ingest(&event);
    let n = alerts.len();

    if n > 0 {
        info!(
            "Ingest PID {} ({}) syscall={} → {} alert(s)",
            req.pid, req.comm, req.syscall_nr, n
        );
        state.push_alerts(alerts.clone()).await;
    }

    (
        StatusCode::OK,
        Json(IngestResponse { alerts_generated: n, alerts }),
    ).into_response()
}

// ─── Handler: GET /api/v1/zeroday/alerts ──────────────────────────────────────

pub async fn get_alerts(
    Extension(state): Extension<Arc<ZeroDayApiState>>,
    Query(query):     Query<AlertsQuery>,
) -> impl IntoResponse {
    let buf = state.recent_alerts.read().await;

    let filtered: Vec<&ZeroDayAlert> = buf.iter()
        .filter(|a| {
            // Filter by severity if requested
            if let Some(ref sev) = query.severity {
                let matches = match sev.to_uppercase().as_str() {
                    "LOW"      => a.severity == ZeroDaySeverity::Low,
                    "MEDIUM"   => a.severity == ZeroDaySeverity::Medium,
                    "HIGH"     => a.severity == ZeroDaySeverity::High,
                    "CRITICAL" => a.severity == ZeroDaySeverity::Critical,
                    _          => true,
                };
                if !matches { return false; }
            }
            // Filter by PID if requested
            if let Some(pid) = query.pid {
                if a.pid != pid { return false; }
            }
            true
        })
        .rev() // Most recent first
        .take(query.limit)
        .collect();

    let count = filtered.len();
    info!("GET /api/v1/zeroday/alerts → {} alerts (limit={})", count, query.limit);

    (
        StatusCode::OK,
        Json(serde_json::json!({
            "count": count,
            "alerts": filtered,
        })),
    )
}

// ─── Handler: GET /api/v1/zeroday/drift ───────────────────────────────────────

pub async fn get_drift(
    Extension(state): Extension<Arc<ZeroDayApiState>>,
) -> impl IntoResponse {
    let raw = state.engine.all_drift_stats();
    let drifts: Vec<DriftEntry> = raw
        .into_iter()
        .map(|(pid, kl)| DriftEntry { pid, kl_divergence: kl })
        .collect();
    let count = drifts.len();

    info!("GET /api/v1/zeroday/drift → {} PIDs tracked", count);
    (StatusCode::OK, Json(DriftResponse { count, drifts }))
}

// ─── Handler: GET /api/v1/zeroday/status ──────────────────────────────────────

pub async fn get_status(
    Extension(state): Extension<Arc<ZeroDayApiState>>,
) -> impl IntoResponse {
    let active_profiles = state.engine.all_profiles().len();
    let total_alerts    = state.recent_alerts.read().await.len();

    (
        StatusCode::OK,
        Json(StatusResponse {
            engine_version:    env!("CARGO_PKG_VERSION"),
            active_profiles,
            total_alerts,
            isolation_trees:   100,
            anomaly_threshold: state.engine.threshold,
        }),
    )
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::detection::zero_day::ZeroDayEngine;

    fn make_state() -> Arc<ZeroDayApiState> {
        ZeroDayApiState::new(Arc::new(ZeroDayEngine::new()))
    }

    #[tokio::test]
    async fn push_alerts_respects_max_cap() {
        let state = make_state();

        // Generate MAX_ALERTS + 100 alerts
        for i in 0..(MAX_ALERTS + 100) {
            let alert = ZeroDayAlert {
                id:               format!("alert-{}", i),
                timestamp:        chrono::Utc::now(),
                pid:              i as u32 % 1000 + 1,
                process_name:     "test".into(),
                detection_method: DetectionMethod::BehavioralAnomaly,
                anomaly_score:    0.9,
                severity:         ZeroDaySeverity::High,
                description:      "test alert".into(),
                mitre_techniques: vec![],
                features:         None,
                exploit_type:     None,
            };
            state.push_alerts(vec![alert]).await;
        }

        let count = state.recent_alerts.read().await.len();
        assert!(count <= MAX_ALERTS, "Alert buffer must not exceed MAX_ALERTS ({} > {})", count, MAX_ALERTS);
    }

    #[tokio::test]
    async fn push_empty_alerts_does_not_panic() {
        let state = make_state();
        state.push_alerts(vec![]).await;
        assert_eq!(state.recent_alerts.read().await.len(), 0);
    }

    #[test]
    fn profile_summary_from_profile() {
        let profiler = crate::detection::zero_day::SyscallProfiler::new();
        use crate::detection::zero_day::SyscallEvent;
        for _ in 0..10 {
            profiler.record(&SyscallEvent::new(1111, 0, "test"));
        }
        let profile = profiler.get_profile(1111).unwrap();
        let summary = ProfileSummary::from(&profile);
        assert_eq!(summary.pid, 1111);
        assert_eq!(summary.event_count, 10);
    }

    #[test]
    fn ingest_request_pid_validation() {
        // Verify that PID=0 would be rejected (logic test, not HTTP test)
        let invalid_pid = 0u32;
        assert_eq!(invalid_pid, 0, "PID 0 should be rejected");

        let valid_pid = 1234u32;
        assert_ne!(valid_pid, 0, "Valid PID should not be 0");
    }
}
